### ISSUE TITLE
BSoD on shutdown with KERNEL_SECURITY_CHECK_FAILURE (corrupt list entry)

### ISSUE THREAD

**Issue by Ralino** [maharmstone/btrfs#87]
I get on about every second shutdown a BSoD with KERNEL_SECURITY_CHECK_FAILURE (FAST_FAIL_CORRUPT_LIST_ENTRY) on Windows 10. I could not find any direct causes which made the shutdown fail or not, but it seems to fail about half the time.

```
KERNEL_SECURITY_CHECK_FAILURE (139)
A kernel component has corrupted a critical data structure.  The corruption
could potentially allow a malicious user to gain control of this machine.
Arguments:
Arg1: 0000000000000003, A LIST_ENTRY has been corrupted (i.e. double remove).
Arg2: ffffcb828bc5a440, Address of the trap frame for the exception that caused the bugcheck
Arg3: ffffcb828bc5a398, Address of the exception record for the exception that caused the bugcheck
Arg4: 0000000000000000, Reserved

EXCEPTION_RECORD:  ffffcb828bc5a398 -- (.exr 0xffffcb828bc5a398)
ExceptionAddress: fffff80bfdd10fe5 (btrfs+0x0000000000010fe5)
   ExceptionCode: c0000409 (Security check failure or stack buffer overrun)
  ExceptionFlags: 00000001
NumberParameters: 1
   Parameter[0]: 0000000000000003
Subcode: 0x3 FAST_FAIL_CORRUPT_LIST_ENTRY
```

The minidump is attached [here](https://github.com/maharmstone/btrfs/files/1802620/031218-5515-01.zip).
I tried installing the debug version as well, but it does not seem to create a log with `DebugLogLevel = 2` and `LogFile = \??\C:\btrfs.log`
